### ISSUE TITLE
Hexo 路由问题

### ISSUE THREAD

**Issue by Cyber-Yin** [zeabur/hexo-template#1]
这个模板生成的所有页面都指向主页，请看浏览器地址栏内容：

![](https://article.biliimg.com/bfs/article/2d4b9a8cf8808fb17be6e0ba12a349c3df0e87b6.png)

![](https://article.biliimg.com/bfs/article/e45a2495e1a6695a3857c79e879da26d07afb512.png)

**Comment by yuaanlin** [comment]
谢谢你的反馈！我们刚刚已经修复了这个问题 🙏

<img width="1195" alt="截圖 2023-02-17 下午2 37 01" src="https://user-images.githubusercontent.com/21105863/219567927-d6879db4-56b1-4a01-9513-d3f64666db7b.png">

如果关于这个问题有其他需要补充的，您可以随时重新开启这个 Issue
